# Generated by Django 5.2.14 on 2026-05-21 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('lecturer', 'Lecturer'), ('course_rep', 'Course Rep'), ('student', 'Student'), ('hod', 'Head of Department')], default='student', max_length=16),
        ),
    ]
