# Generated by Django 5.2.17 on 2026-08-09 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_must_change_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('lecturer', 'Lecturer'), ('course_rep', 'Course Rep'), ('student', 'Student'), ('hod', 'Head of Department'), ('vice_chancellor', 'Vice Chancellor')], default='student', max_length=16),
        ),
    ]
