# Generated by Django 5.2.17 on 2026-08-09 02:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ('code',)},
        ),
        migrations.AddField(
            model_name='course',
            name='unit',
            field=models.PositiveSmallIntegerField(default=0, help_text='Credit units.', validators=[django.core.validators.MaxValueValidator(12)]),
        ),
    ]
